apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal-dev.fullname" . }}-headless
  labels:
    {{- include "temporal-dev.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.service }}
      targetPort: service
      protocol: TCP
      name: service
    - port: {{ .Values.service.ports.web }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "temporal-dev.selectorLabels" . | nindent 4 }}
